[package]
name = "wechat-summary-gui"
build = "build.rs"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
eframe.workspace = true
serde.workspace = true
serde_json.workspace = true
toml_edit.workspace = true
wechat-summary-core = { path = "../core" }
